name: api schedule automation test

on: 
    push:
    schedule:
      - cron: '1 * * * *'

jobs:
  frequent-test:
    runs-on: ubuntu-latest

    steps:
        # check repository
      - name: Checkout
        uses: actions/checkout@v4.2.2

        # install node
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
          
        # run test
      - name: run test
        run: npm run apitest
