name: API Schedule Automation Test

on:
  push:
  schedule:
    - cron: '1 * * * *'

jobs:
  frequent-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Set up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # specify your desired version of Node.js


      - name: Install Mocha globally
        run: npm install -g mocha  mochawesome dotenv
        
      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the tests
      - name: Run API test
        run: npm run apitest


        # Upload test report as an artifact
      - name: Upload Mocha test report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: ./mochawesome-report  

 # Optionally, you can display the HTML report as a comment in the workflow run
      - name: Upload Mochawesome HTML report to GitHub
        run: |
          cp mochawesome-report/mochawesome.html $GITHUB_WORKSPACE/mochawesome-report.html
        if: always()
     
