name: api schedule automation test

on: 
    schedule:
      - cron: '1 * * * *'

jobs:
  frequent-test:
    runs-on: ubuntu-latest

    steps:
        # check repository
      - name: Checkout
        uses: actions/checkout@v4.2.2

        # run test
      - name: run test
        run: npm run apitest
