name: API Schedule Automation Test

on:
  push:
  schedule:
    - cron: '1 * * * *'

jobs:
  frequent-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Set up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '16'  # specify your desired version of Node.js


      - name: Install Mocha globally
        run: npm install -g mocha  mochawesome dotenv
        
      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the tests
      - name: Run API test
        run: npm run apitest
